#!/bin/sh
#.make.sh

dir=~/configFiles
olddir=~/configFiles_old
dotFilesFolder=$dir/dotFiles
dotFiles=".bashrc .bash_aliases .vimrc .gitconfig .zshrc"

echo "backing up existing configfiles to $olddir"

if [ ! -d $olddir ]; then 
  mkdir -p $olddir
  echo "created $olddir ..."
fi

for file in $dotFiles; do
  if [ -h ~/$file ]; then 
      echo "deleting existing symbolic link to $file..."
      rm ~/$file
  elif [ -e ~/$file ]; then 
      echo "Moving existing file to backup folder ..."
      mv ~/$file $olddir
  fi
      echo "Creating Symlink to $file in home directory..."
      ln -s $dotFilesFolder/$file ~/$file
done
